apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mdb
  name: db-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
