apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mdb
  name: dbmovie
  labels:
    app: dbmovie
spec:
  selector:
    matchLabels:
      app: dbmovie
  template:
    metadata:
      labels:
        app: dbmovie
    spec:
      containers:
      - name: dbmovie
        image: postgres:17.5
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          ## Direct definition
          # - name: POSTGRES_PASSWORD
          #   value: "superpassword"
          # - name: POSTGRES_USER
          #   value: "movie"
          # - name: POSTGRES_DB
          #   value: "dbmovie"
          ## From configMap or secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: POSTGRES_DB
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: db-init
          - mountPath: /var/lib/postgresql/data
            name: db-storage
      volumes:
        - name: db-init
          configMap:
            name: db-init
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc


          # TODO: persistent volume pour la Data
          # TODO: rolling update / rollback