apiVersion: v1
kind: Service
metadata:
  name: echosolo-service
spec:
  type: NodePort
  selector:
    run: echosolo
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30666 # range 30000-32767
