apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
  - port: 85 # exposed port (load balancer)
    targetPort: 80 # container port
