services:

  api: 
    image: movieapi:0.2
    restart: always
    environment:
      DB_URL: postgresql+psycopg2://scott:tiger@localhost:5432/mydatabase
    ports:
      - ${API_PORT:-8080}:8080